{% set name = "xorg-libfontenc" %}
{% set version = "1.1.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://www.x.org/releases/individual/lib/libfontenc-{{ version }}.tar.xz
  sha256: "7b02c3d405236e0d86806b1de9d6868fe60c313628b38350b032914aa4fd14c6"

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - pkg-config
    - make
    - xorg-xorgproto
    - zlib
  host:
    - libzlib {{ libzlib }}
    - xorg-xorgproto {{ xorg_xorgproto }}
  run:
    # bounds through run_exports
    - libzlib
    - xorg-xorgproto

test:
  requires:
    - pkg-config
  commands:
    - pkg-config --exists fontenc
    - test -f $PREFIX/lib/libfontenc.dylib  # [osx]
    - test -f $PREFIX/lib/libfontenc.so     # [linux]

about:
  home: https://www.x.org/
  summary: The X.Org font encoding library
  license: MIT
  license_family: MIT
  license_file: COPYING
  description: The X.Org font encoding library
  doc_url: https://www.x.org/wiki/Documentation/
  dev_url: https://gitlab.freedesktop.org/xorg/lib/libfontenc