{% set name = "xorg-libfontenc" %}
{% set version = "1.1.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://www.x.org/releases/individual/lib/libfontenc-{{ version }}.tar.xz
  sha256: "7b02c3d405236e0d86806b1de9d6868fe60c313628b38350b032914aa4fd14c6"

build:
  number: 0

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - pkg-config  # [unix]
    - make  # [unix]
    - msys2-pkg-config  # [win]
    - msys2-make # [win]
    - xorg-xorgproto
    - zlib
  host:
    - zlib
    - xorg-xorgproto
  run:
    - zlib

test:
  requires:
    - pkg-config  # [unix]
    - msys2-pkg-config  # [win]
  commands:
    - pkg-config --exists fontenc
    - test -f $PREFIX/lib/libfontenc.dylib  # [osx]
    - test -f $PREFIX/lib/libfontenc.so     # [linux]
    - test -f $PREFIX/lib/libfontenc.dll # [win]

about:
  home: https://www.x.org/
  summary: The X.Org font encoding library
  license: MIT
  license_family: MIT
  license_file: COPYING
  description: The X.Org font encoding library
  doc_url: https://www.x.org/wiki/Documentation/
  dev_url: https://gitlab.freedesktop.org/xorg/lib/libfontenc